# Numpy stack consists of numpy, pandas, scipy and matplotlib

# This file is primarily for numpy



a list can contain an integer, char, boolean and another list in python, but a numpy array is specifically designed for numerical work.


In [15]:
import numpy as np


x = np.array([
    [1.2, 5.0, 7.1],
    [2.4, 4.2, 8.0],
    [3.1, 6.3, 6.8],
])

x.shape


(3, 3)

In [17]:

x.size

9

In [30]:
x.ndim



2

In [22]:
x.dtype

dtype('float64')

IN ml rows = observations/samples
and columns = features and measurements.

so if an array is shaped (10000, 3). it means it has 10000 observations and 3 features per observation.

In [31]:
L = [1, 2, 3]
A = np.array([1, 2, 3])

In [33]:
L + [4]

[1, 2, 3, 4]

In [34]:
A + 4

array([5, 6, 7])

In [35]:
A + np.array([5, 6, 7])

array([ 6,  8, 10])

In [36]:
# multiplacation

2 * L

[1, 2, 3, 1, 2, 3]

In [37]:
2 * A

array([2, 4, 6])

In [38]:
# mathematical functions in numpy arrays
np.sqrt(A)
np.log(A)
np.exp(A)
np.sin(A)
np.tanh(A)
A ** 2

array([1, 4, 9])

In [41]:
X = np.array([
    [10, 100],
    [20, 200],
    [30, 300],
])

column_means = X.mean(axis=0)
print(column_means)
centred = X - column_means

110.0


In [59]:
c = np.array([[2, 3],
              [4, 5]])

In [60]:
np.linalg.eig(c)

EigResult(eigenvalues=array([-0.27491722+0.j,  7.27491722+0.j]), eigenvectors=array([[-0.79681209+0.j, -0.49436913+0.j],
       [ 0.60422718+0.j, -0.86925207+0.j]]))

In [63]:
np.linalg.inv(c).dot(c)

array([[1., 0.],
       [0., 1.]])

In [67]:
Lam, V = np.linalg.eig(c)
print(Lam, V)

[-0.27491722+0.j  7.27491722+0.j] [[-0.79681209+0.j -0.49436913+0.j]
 [ 0.60422718+0.j -0.86925207+0.j]]


In [69]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [70]:

np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
np.random.random((2, 3))

array([[0.03751436, 0.97709807, 0.08069365],
       [0.25921425, 0.65673241, 0.39617197]])

In [74]:
np.random.randn(2, 3)

array([[-0.37999976, -1.769146  ,  0.53200165],
       [-0.71521991,  0.83206523, -1.06278368]])

In [82]:
R = np.random.randn(10000)


In [83]:
R.mean()

np.float64(-0.010150240671163506)

In [84]:
R = np.random.randn(10000, 3)

In [85]:
R.mean(axis= 0) # calculates the mean of each column

array([-0.00298372, -0.0117455 , -0.00707099])

In [87]:
R.mean(axis= 1).shape # calculates the mean of each row


(10000,)

In [88]:
np.cov(R).shape

(10000, 10000)

In [89]:
np.random.randint(0 , 10 , size = (3, 3))

array([[0, 1, 4],
       [4, 0, 4],
       [2, 5, 1]])